### ISSUE TITLE
Clicking "Maximise" button in Windows causes crash

### ISSUE THREAD

**Issue by PhonicUK** [maierfelix/tiny-rtx#2]
```
file:///C:/tiny-rtx/src/utils.mjs:12
        throw new Error(`Vulkan assertion failed with ${key}`);
        ^

Error: Vulkan assertion failed with VK_ERROR_OUT_OF_DATE_KHR
    at ASSERT_VK_RESULT (file:///C:/tiny-rtx/src/utils.mjs:12:15)
    at RayTracingDemo.VulkanApplication.drawDefaultFrame (file:///C:/tiny-rtx/src/VulkanApplication.mjs:126:3)
    at RayTracingDemo.drawFrame (file:///C:/tiny-rtx/src/index.mjs:174:8)
    at Timeout.drawLoop [as _onTimeout] (file:///C:/tiny-rtx/src/index.mjs:152:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-rtx@0.0.1 start: `node --experimental-modules ./main.mjs --verbose-log`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-rtx@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by russelldc** [comment]
I'm seeing this issue on my machine as well.

Seems to be related to this section of the Vulkan docs:
https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation

**Comment by maierfelix** [comment]
I didn't add swapchain recreation yet. If I get back to this project, then I'll add it
