### ISSUE TITLE
The requested module 'nvk-essentials' does not provide an export named 'GLSL'

### ISSUE THREAD

**Issue by PatrickJnr** [maierfelix/tiny-rtx#3]
I seem to keep getting this issue :(

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tiny-rtx@0.0.1~prestart: tiny-rtx@0.0.1
6 info lifecycle tiny-rtx@0.0.1~start: tiny-rtx@0.0.1
7 verbose lifecycle tiny-rtx@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle tiny-rtx@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\GitHubStuff\tiny-rtx\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Python38\Scripts\;C:\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\vim\vim80;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;;C:\Users\User\AppData\Local\Markdown Monster;C:\Users\User\AppData\Roaming\npm
9 verbose lifecycle tiny-rtx@0.0.1~start: CWD: F:\GitHubStuff\tiny-rtx
10 silly lifecycle tiny-rtx@0.0.1~start: Args: [ '/d /s /c', 'node --experimental-modules ./main.mjs --verbose-log' ]
11 silly lifecycle tiny-rtx@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle tiny-rtx@0.0.1~start: Failed to exec start script
13 verbose stack Error: tiny-rtx@0.0.1 start: `node --experimental-modules ./main.mjs --verbose-log`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid tiny-rtx@0.0.1
15 verbose cwd F:\GitHubStuff\tiny-rtx
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.9.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error tiny-rtx@0.0.1 start: `node --experimental-modules ./main.mjs --verbose-log`
22 error Exit status 1
23 error Failed at the tiny-rtx@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

That's from the log file.
[2019-08-21T09_01_24_044Z-debug.log](https://github.com/maierfelix/tiny-rtx/files/3524430/2019-08-21T09_01_24_044Z-debug.log)

**Comment by maierfelix** [comment]
@GrimTech I've made some changes to a library this project uses and forgot to update this one, sorry for that!

**Comment by PatrickJnr** [comment]
> @GrimTech I've made some changes to a library this project uses and forgot to update this one, sorry for that!

No worries!
